/**
 * Valores resueltos (modo actual) desde Figma — frame kubo.color
 * https://www.figma.com/design/XhvIIW42BM1u2ViM0MaBR0/Calipso-2.0?node-id=2080-939
 * Sincronizar cuando cambien variables en Figma.
 */
export const figmaColorTokens: Record<string, string> = {
  "ref/color/brand/50": "#e6f5e6",
  "ref/color/brand/100": "#ddf0dd",
  "ref/color/brand/200": "#bfe7c1",
  "ref/color/brand/300": "#8fd88f",
  "ref/color/brand/400": "#5fc65f",
  "ref/color/brand/500": "#2e9f30",
  "ref/color/brand/600": "#278a29",
  "ref/color/brand/700": "#1f6f21",
  "ref/color/brand/800": "#165517",
  "ref/color/brand/900": "#0e3a0f",
  "ref/color/neutral/0": "#ffffff",
  "ref/color/neutral/50": "#f7f7f8",
  "ref/color/neutral/100": "#ededee",
  "ref/color/neutral/200": "#d7d7da",
  "ref/color/neutral/300": "#bfc0c5",
  "ref/color/neutral/400": "#9a9ba1",
  "ref/color/neutral/500": "#73747a",
  "ref/color/neutral/600": "#57585e",
  "ref/color/neutral/700": "#414047",
  "ref/color/neutral/800": "#2b2a30",
  "ref/color/neutral/900": "#1c1b20",
  "ref/color/neutral/1000": "#000000",
  "ref/color/accent/50": "#fbfefe",
  "ref/color/accent/100": "#f2fafa",
  "ref/color/accent/200": "#c7e8e8",
  "ref/color/accent/300": "#addcdc",
  "ref/color/accent/400": "#8fcfcf",
  "ref/color/accent/500": "#6fbfbf",
  "ref/color/accent/600": "#4faaaa",
  "ref/color/accent/700": "#368c8c",
  "ref/color/accent/800": "#236969",
  "ref/color/accent/900": "#174b4b",
  "ref/color/feedback/error/50": "#fdeeee",
  "ref/color/feedback/error/100": "#fadada",
  "ref/color/feedback/error/200": "#f5b8b8",
  "ref/color/feedback/error/300": "#ee8f8f",
  "ref/color/feedback/error/400": "#e05f5f",
  "ref/color/feedback/error/500": "#d64545",
  "ref/color/feedback/error/600": "#b83a3a",
  "ref/color/feedback/error/700": "#932e2e",
  "ref/color/feedback/error/800": "#6f2121",
  "ref/color/feedback/error/900": "#4d1515",
  "ref/color/feedback/warning/50": "#fff8eb",
  "ref/color/feedback/warning/100": "#fef0d2",
  "ref/color/feedback/warning/200": "#fde1a6",
  "ref/color/feedback/warning/300": "#fbcb6d",
  "ref/color/feedback/warning/400": "#f7b23a",
  "ref/color/feedback/warning/500": "#e89a1c",
  "ref/color/feedback/warning/600": "#c87f14",
  "ref/color/feedback/warning/700": "#9e6410",
  "ref/color/feedback/warning/800": "#74480c",
  "ref/color/feedback/warning/900": "#4a2e08",
  "ref/color/feedback/info/50": "#eef6fb",
  "ref/color/feedback/info/100": "#dcecf6",
  "ref/color/feedback/info/200": "#b9d9ed",
  "ref/color/feedback/info/300": "#8fc2e2",
  "ref/color/feedback/info/400": "#5ea6d4",
  "ref/color/feedback/info/500": "#2f89c5",
  "ref/color/feedback/info/600": "#2674a7",
  "ref/color/feedback/info/700": "#1e5d86",
  "ref/color/feedback/info/800": "#164564",
  "ref/color/feedback/info/900": "#0f2e42",
  "ref/color/feedback/success/50": "#eef8f1",
  "ref/color/feedback/success/100": "#dff1e5",
  "ref/color/feedback/success/200": "#bfe4cc",
  "ref/color/feedback/success/300": "#8fd2a6",
  "ref/color/feedback/success/400": "#5fbe80",
  "ref/color/feedback/success/500": "#2fa45e",
  "ref/color/feedback/success/600": "#278b50",
  "ref/color/feedback/success/700": "#1f6f40",
  "ref/color/feedback/success/800": "#175631",
  "ref/color/feedback/success/900": "#0f3d23",
  "semantic/color/text/primary": "#1c1b20",
  "semantic/color/text/onBrand": "#ffffff",
  "semantic/color/text/secondary": "#57585e",
  "semantic/color/text/tertiary": "#9a9ba1",
  "semantic/color/text/inverse": "#d7d7da",
  "semantic/color/text/disabled": "#9a9ba1",
  "semantic/color/text/brand": "#1f6f21",
  "semantic/color/text/accent": "#236969",
  "semantic/color/text/onAccent": "#ffffff",
  "semantic/color/text/danger": "#b83a3a",
  "semantic/color/text/dangerStrong": "#932e2e",
  "semantic/color/text/onDanger": "#ffffff",
  "semantic/color/text/warning": "#74480c",
  "semantic/color/text/onWarning": "#ffffff",
  "semantic/color/text/success": "#1f6f40",
  "semantic/color/text/onSuccess": "#ffffff",
  "semantic/color/text/info": "#1e5d86",
  "semantic/color/text/onInfo": "#ffffff",
  "semantic/color/text/linkDefault": "#1f6f21",
  "semantic/color/text/linkHover": "#165517",
  "semantic/color/text/linkPressed": "#0e3a0f",
  "semantic/color/bg/inverse": "#1c1b20",
  "semantic/color/bg/brand": "#1f6f21",
  "semantic/color/bg/danger": "#b83a3a",
  "semantic/color/bg/surface": "#ffffff",
  "semantic/color/bg/warning": "#e89a1c",
  "semantic/color/bg/success": "#2fa45e",
  "semantic/color/bg/info": "#2f89c5",
  "semantic/color/bg/inverseElevated": "#00000033",
  "semantic/color/bg/canvas": "#2b2a30",
  "semantic/color/bg/subtle": "#ededee",
  "semantic/color/bg/disabled": "#bfc0c5",
  "semantic/color/bg/brandSoft": "#ddf0dd",
  "semantic/color/bg/brandMuted": "#e6f5e6",
  "semantic/color/bg/successSoft": "#bfe4cc",
  "semantic/color/bg/warningSoft": "#fde1a6",
  "semantic/color/bg/dangerSoft": "#f5b8b8",
  "semantic/color/bg/dangerMuted": "#fadada",
  "semantic/color/bg/infoSoft": "#b9d9ed",
  "semantic/color/bg/accentSoft": "#addcdc",
  "semantic/color/bg/overlay": "#00000066",
  "semantic/color/bg/successMuted": "#dff1e5",
  "semantic/color/bg/warningMuted": "#fef0d2",
  "semantic/color/bg/infoMuted": "#dcecf6",
  "semantic/color/bg/accentMuted": "#c7e8e8",
  "semantic/color/bg/accent": "#8fcfcf",
  "semantic/color/icon/tertiary": "#9a9ba1",
  "semantic/color/icon/inverse": "#1c1b20",
  "semantic/color/icon/disabled": "#57585e",
  "semantic/color/icon/brand": "#e6f5e6",
  "semantic/color/icon/onBrand": "#1c1b20",
  "semantic/color/icon/accent": "#c7e8e8",
  "semantic/color/icon/onAccent": "#1c1b20",
  "semantic/color/icon/danger": "#f5b8b8",
  "semantic/color/icon/onDanger": "#1c1b20",
  "semantic/color/icon/warning": "#fde1a6",
  "semantic/color/icon/onWarning": "#1c1b20",
  "semantic/color/icon/success": "#bfe7c1",
  "semantic/color/icon/onSuccess": "#1c1b20",
  "semantic/color/icon/info": "#b9d9ed",
  "semantic/color/icon/onInfo": "#1c1b20",
  "semantic/color/icon/primary": "#1c1b20",
  "semantic/color/icon/secondary": "#57585e",
  "semantic/color/icon/dangerStrong": "#932e2e",
  "semantic/color/border/subtle": "#ededee",
  "semantic/color/border/default": "#d7d7da",
  "semantic/color/border/strong": "#bfc0c5",
  "semantic/color/border/emphasis": "#9a9ba1",
  "semantic/color/border/inverse": "#ffffff",
  "semantic/color/border/brand": "#1f6f21",
  "semantic/color/border/accent": "#8fcfcf",
  "semantic/color/border/accentStrong": "#368c8c",
  "semantic/color/border/focus": "#5ea6d4",
  "semantic/color/border/info": "#8fc2e2",
  "semantic/color/border/success": "#8fd2a6",
  "semantic/color/border/warning": "#fbcb6d",
  "semantic/color/border/danger": "#b83a3a",
  "semantic/color/border/dangerSoft": "#ee8f8f",
  "semantic/color/border/disabled": "#bfc0c5",
  "semantic/color/border/overlay": "#0000008f",
};

/** CSS custom property: ref/color/brand/50 → --ref-color-brand-50 */
export function figmaPathToCssVar(path: string): string {
  return `--${path.replaceAll("/", "-")}`;
}

export function colorCssBlock(): string {
  const lines = Object.entries(figmaColorTokens).map(
    ([k, v]) => `  ${figmaPathToCssVar(k)}: ${v};`,
  );
  return `:root {\n${lines.join("\n")}\n}\n`;
}
